name: scanntech-operaciones # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.5.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Herramientas que entregan reportes de clientes # 79 char long summary
description: |
    Resuelve problemas de suma en los reportes de citi
    Permite obtener los reportes de ater y arba a partir de un excel
    Permite eliminar puntos de venta del reporte citi ventas

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: MIT

apps:
    arba:
        command: bin/arba
        plugs:
            - home
    ater:
        command: bin/ater
        plugs:
            - home
    padron:
        command: bin/padron
        plugs:
            - home
    scanntech-operaciones:
        command: bin/scanntech-operaciones
        plugs:
            - home
    citi:
        command: bin/citi
        plugs:
            - home
parts:
  scanntech-operaciones:
    # See 'snapcraft plugins'
    plugin: python
    build-packages:
      - git
    python-packages:
      - pip
      - wheel
      - setuptools
      - git+https://github.com/AlopexMM/fiscal-tools.git # Install from a git repo
    source: https://github.com/AlopexMM/scanntech-apps.git

architectures:
  - build-on: amd64
    run-on: amd64
