name: scanntech-operaciones # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1-11' # just for humans, typically '1.2+git' or '1.3.2'
summary: Herramientas que entregan reportes de clientes # 79 char long summary
description: |
    Te permite resolver el reporte de ATER a partir del reporte de Z fiscales

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: MIT

apps:
    ater:
        command: bin/ater
        plugs:
            - home
    scanntech-operaciones:
        command: bin/scanntech-operaciones
        plugs:
            - home
parts:
  scanntech-operaciones:
    # See 'snapcraft plugins'
    plugin: python
    build-packages:
      - git
    python-packages:
      - pip
      - wheel
      - setuptools
      - git+https://github.com/AlopexMM/fiscal-tools.git # Install from a git repo
    source: https://github.com/AlopexMM/scanntech-apps.git
